In [2]:
import pandas as pd

ks = pd.read_csv('kickstarter-projects/ks-projects-201801.csv',
                 parse_dates=['deadline', 'launched'])
ks.head(10)

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,0.00,0.00,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,100.00,2421.00,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.00,failed,3,US,220.00,220.00,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.00,failed,1,US,1.00,1.00,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.00,canceled,14,US,1283.00,1283.00,19500.00
5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26 13:38:27,52375.00,successful,224,US,52375.00,52375.00,50000.00
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1205.00,1205.00,1000.00
7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01 20:05:12,453.00,failed,40,US,453.00,453.00,25000.00
8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24 18:14:43,8233.00,canceled,58,US,8233.00,8233.00,125000.00
9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11 21:55:48,6240.57,canceled,43,US,6240.57,6240.57,65000.00

In [3]:
pd.unique(ks.state)

array(['failed', 'canceled', 'successful', 'live', 'undefined',
       'suspended'], dtype=object)

In [4]:
ks.state.value_counts()

failed        197719
successful    133956
canceled       38779
undefined       3562
live            2799
suspended       1846
Name: state, dtype: int64

In [5]:
ks = ks.query('state != "live"')

ks = ks.assign(outcome=(ks['state'] == 'successful').astype(int))

In [6]:
ks = ks.assign(hour=ks.launched.dt.hour,
              day=ks.launched.dt.day,
              month=ks.launched.dt.month,
              year=ks.launched.dt.year)
ks.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,outcome,hour,day,month,year
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,0,12,11,8,2015
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,0,4,2,9,2017
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,0,0,12,1,2013
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,0,3,17,3,2012
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,0,8,4,7,2015

In [7]:
from sklearn.preprocessing import LabelEncoder

cat_features = ['category', 'currency', 'country']
encoder = LabelEncoder()

encoded = ks[cat_features].apply(encoder.fit_transform)
encoded.head(10)

   category  currency  country
0       108         5        9
1        93        13       22
2        93        13       22
3        90        13       22
4        55        13       22
5       123        13       22
6        58        13       22
7        41        13       22
8       113        13       22
9        39        13       22

In [8]:
data = ks[['goal', 'hour', 'day', 'month', 'year', 'outcome']].join(encoded)
data.head()

      goal  hour  day  month  year  outcome  category  currency  country
0   1000.0    12   11      8  2015        0       108         5        9
1  30000.0     4    2      9  2017        0        93        13       22
2  45000.0     0   12      1  2013        0        93        13       22
3   5000.0     3   17      3  2012        0        90        13       22
4  19500.0     8    4      7  2015        0        55        13       22

In [9]:
valid_fraction = 0.1
valid_size = int(len(data) * valid_fraction)

train = data[:-2 * valid_size]
valid = data[-2 * valid_size:-valid_size]
test = data[-valid_size:]

In [10]:
for each in [train, valid, test]:
    print(f"Outcome fraction = {each.outcome.mean():.4f}")

Outcome fraction = 0.3570
Outcome fraction = 0.3539
Outcome fraction = 0.3542

In [12]:
import lightgbm as lgb

feature_cols = train.columns.drop('outcome')

dtrain = lgb.Dataset(train[feature_cols], label=train['outcome'])
dvalid = lgb.Dataset(valid[feature_cols], label=valid['outcome'])

param = {'num_leaves': 64, 'objective': 'binary'}
param['metric'] = 'auc'
num_round = 1000
bst = lgb.train(param, dtrain, num_round, valid_sets=[dvalid], early_stopping_rounds=10, 
                verbose_eval=True)

[1]	valid_0's auc: 0.694192
Training until validation scores don't improve for 10 rounds.
[2]	valid_0's auc: 0.697026
[3]	valid_0's auc: 0.70002
[4]	valid_0's auc: 0.701645
[5]	valid_0's auc: 0.70601
[6]	valid_0's auc: 0.707926
[7]	valid_0's auc: 0.70945
[8]	valid_0's auc: 0.710437
[9]	valid_0's auc: 0.712047
[10]	valid_0's auc: 0.713417
[11]	valid_0's auc: 0.714648
[12]	valid_0's auc: 0.715791
[13]	valid_0's auc: 0.717431
[14]	valid_0's auc: 0.718216
[15]	valid_0's auc: 0.719381
[16]	valid_0's auc: 0.720884
[17]	valid_0's auc: 0.721617
[18]	valid_0's auc: 0.722789
[19]	valid_0's auc: 0.723307
[20]	valid_0's auc: 0.72501
[21]	valid_0's auc: 0.725721
[22]	valid_0's auc: 0.727384
[23]	valid_0's auc: 0.728268
[24]	valid_0's auc: 0.72865
[25]	valid_0's auc: 0.729141
[26]	valid_0's auc: 0.729552
[27]	valid_0's auc: 0.730459
[28]	valid_0's auc: 0.731047
[29]	valid_0's auc: 0.732472
[30]	valid_0's auc: 0.732801
[31]	valid_0's auc: 0.733166
[32]	valid_0's auc: 0.734182
[33]	valid_0's auc: 0.734472
[34]	valid_0's auc: 0.735074
[35]	valid_0's auc: 0.735738
[36]	valid_0's auc: 0.735856
[37]	valid_0's auc: 0.736747
[38]	valid_0's auc: 0.737116
[39]	valid_0's auc: 0.737297
[40]	valid_0's auc: 0.73744
[41]	valid_0's auc: 0.737789
[42]	valid_0's auc: 0.737847
[43]	valid_0's auc: 0.738086
[44]	valid_0's auc: 0.738376
[45]	valid_0's auc: 0.738509
[46]	valid_0's auc: 0.739245
[47]	valid_0's auc: 0.739561
[48]	valid_0's auc: 0.739662
[49]	valid_0's auc: 0.739738
[50]	valid_0's auc: 0.739863
[51]	valid_0's auc: 0.73994
[52]	valid_0's auc: 0.740423
[53]	valid_0's auc: 0.740466
[54]	valid_0's auc: 0.740529
[55]	valid_0's auc: 0.741066
[56]	valid_0's auc: 0.74112
[57]	valid_0's auc: 0.741285
[58]	valid_0's auc: 0.741403
[59]	valid_0's auc: 0.741591
[60]	valid_0's auc: 0.741632
[61]	valid_0's auc: 0.741989
[62]	valid_0's auc: 0.742007
[63]	valid_0's auc: 0.742152
[64]	valid_0's auc: 0.742319
[65]	valid_0's auc: 0.742416
[66]	valid_0's auc: 0.742501
[67]	valid_0's auc: 0.742604
[68]	valid_0's auc: 0.742779
[69]	valid_0's auc: 0.742934
[70]	valid_0's auc: 0.742964
[71]	valid_0's auc: 0.742945
[72]	valid_0's auc: 0.74295
[73]	valid_0's auc: 0.743061
[74]	valid_0's auc: 0.743195
[75]	valid_0's auc: 0.743198
[76]	valid_0's auc: 0.743263
[77]	valid_0's auc: 0.743313
[78]	valid_0's auc: 0.743352
[79]	valid_0's auc: 0.74336
[80]	valid_0's auc: 0.743558
[81]	valid_0's auc: 0.743577
[82]	valid_0's auc: 0.74361
[83]	valid_0's auc: 0.743618
[84]	valid_0's auc: 0.743721
[85]	valid_0's auc: 0.74376
[86]	valid_0's auc: 0.743767
[87]	valid_0's auc: 0.743845
[88]	valid_0's auc: 0.743854
[89]	valid_0's auc: 0.743855
[90]	valid_0's auc: 0.743903
[91]	valid_0's auc: 0.743952
[92]	valid_0's auc: 0.743999
[93]	valid_0's auc: 0.744033
[94]	valid_0's auc: 0.744101
[95]	valid_0's auc: 0.744146
[96]	valid_0's auc: 0.744494
[97]	valid_0's auc: 0.744516
[98]	valid_0's auc: 0.744631
[99]	valid_0's auc: 0.744678
[100]	valid_0's auc: 0.74473
[101]	valid_0's auc: 0.744713
[102]	valid_0's auc: 0.744797
[103]	valid_0's auc: 0.74485
[104]	valid_0's auc: 0.744873
[105]	valid_0's auc: 0.745315
[106]	valid_0's auc: 0.745421
[107]	valid_0's auc: 0.745417
[108]	valid_0's auc: 0.745469
[109]	valid_0's auc: 0.745479
[110]	valid_0's auc: 0.745487
[111]	valid_0's auc: 0.745863
[112]	valid_0's auc: 0.745872
[113]	valid_0's auc: 0.745915
[114]	valid_0's auc: 0.745953
[115]	valid_0's auc: 0.745919
[116]	valid_0's auc: 0.745919
[117]	valid_0's auc: 0.745969
[118]	valid_0's auc: 0.74629
[119]	valid_0's auc: 0.746331
[120]	valid_0's auc: 0.74634
[121]	valid_0's auc: 0.746324
[122]	valid_0's auc: 0.746573
[123]	valid_0's auc: 0.746602
[124]	valid_0's auc: 0.746616
[125]	valid_0's auc: 0.7466
[126]	valid_0's auc: 0.746583
[127]	valid_0's auc: 0.74663
[128]	valid_0's auc: 0.746628
[129]	valid_0's auc: 0.746623
[130]	valid_0's auc: 0.746641
[131]	valid_0's auc: 0.746647
[132]	valid_0's auc: 0.746672
[133]	valid_0's auc: 0.746648
[134]	valid_0's auc: 0.746682
[135]	valid_0's auc: 0.74671
[136]	valid_0's auc: 0.746716
[137]	valid_0's auc: 0.746698
[138]	valid_0's auc: 0.746868
[139]	valid_0's auc: 0.746899
[140]	valid_0's auc: 0.746899
[141]	valid_0's auc: 0.747047
[142]	valid_0's auc: 0.747045
[143]	valid_0's auc: 0.74705
[144]	valid_0's auc: 0.747091
[145]	valid_0's auc: 0.747102
[146]	valid_0's auc: 0.7473
[147]	valid_0's auc: 0.747294
[148]	valid_0's auc: 0.747297
[149]	valid_0's auc: 0.747358
[150]	valid_0's auc: 0.747377
[151]	valid_0's auc: 0.747398
[152]	valid_0's auc: 0.747403
[153]	valid_0's auc: 0.747418
[154]	valid_0's auc: 0.747412
[155]	valid_0's auc: 0.747415
[156]	valid_0's auc: 0.74744
[157]	valid_0's auc: 0.747471
[158]	valid_0's auc: 0.747485
[159]	valid_0's auc: 0.747484
[160]	valid_0's auc: 0.747479
[161]	valid_0's auc: 0.747515
[162]	valid_0's auc: 0.747515
[163]	valid_0's auc: 0.747519
[164]	valid_0's auc: 0.747541
[165]	valid_0's auc: 0.747549
[166]	valid_0's auc: 0.747544
[167]	valid_0's auc: 0.747538
[168]	valid_0's auc: 0.747541
[169]	valid_0's auc: 0.747579
[170]	valid_0's auc: 0.747578
[171]	valid_0's auc: 0.747591
[172]	valid_0's auc: 0.747555
[173]	valid_0's auc: 0.747529
[174]	valid_0's auc: 0.74754
[175]	valid_0's auc: 0.747513
[176]	valid_0's auc: 0.747488
[177]	valid_0's auc: 0.747513
[178]	valid_0's auc: 0.747526
[179]	valid_0's auc: 0.747511
[180]	valid_0's auc: 0.747528
[181]	valid_0's auc: 0.747544
Early stopping, best iteration is:
[171]	valid_0's auc: 0.747591

In [14]:
from sklearn import metrics

ypred = bst.predict(test[feature_cols])
score = metrics.roc_auc_score(test['outcome'], ypred)
print(f'Test AUC score: {score}')

Test AUC score: 0.747615303004287